.PHONY: clean All

All:
	@echo "----------Building project:[ sectionchallenge - Debug ]----------"
	@cd "sectionchallenge" && "$(MAKE)" -f  "sectionchallenge.mk"
clean:
	@echo "----------Cleaning project:[ sectionchallenge - Debug ]----------"
	@cd "sectionchallenge" && "$(MAKE)" -f  "sectionchallenge.mk" clean
