.PHONY: clean All

All:
	@echo "----------Building project:[ SectionAssignment - Debug ]----------"
	@cd "SectionAssignment" && "$(MAKE)" -f  "SectionAssignment.mk"
clean:
	@echo "----------Cleaning project:[ SectionAssignment - Debug ]----------"
	@cd "SectionAssignment" && "$(MAKE)" -f  "SectionAssignment.mk" clean
